### ISSUE TITLE
Theory-to-Practice: add example project

### ISSUE THREAD

**Issue by gofilipa** [DHRI-Curriculum/python#23]
Looking for another example for the "Projects That Use These Skills" section. Already have included the NEH impact index, which showcases Python for web dev (Flask) and scraping data. 

I want this section to give a more well rounded sense of what can be done with Python. Is there an interesting (preferably scholarly or student) project that showcases data visualization with python? Will love to hear suggestions! Thank you.

**Comment by szweibel** [comment]
Adding the Data 4 Public Good 2019 project.

**Comment by kallewesterling** [comment]
I really like the idea of using our own projects as much as we can! Thanks for adding @szweibel !

**Comment by gofilipa** [comment]
Just merged your changes, @szweibel. Gonna close out this issue. Thank you Steve!
