### ISSUE TITLE
Theory-to-Practice: revise discussion questions

### ISSUE THREAD

**Issue by gofilipa** [DHRI-Curriculum/python#24]
The current questions center more on basic data and ethics: 

- What kind of data do you use in your research, and how do you acquire that data?
- What questions do you have about your data? What kind of manipulations would you want to perform on that data?
- What are the limitations of your data? Does your data suffice to show the full picture of your topic? What does it fail to capture?

Instead, add questions that review the major concepts from the workshop, such as variables, data types, functions, control flow, etc.

**Comment by kallewesterling** [comment]
That would be great @gofilipa.

Wanted to loop @dyoong in here — perhaps this would fit better with what we were talking about in our meeting yesterday!

**Comment by kallewesterling** [comment]
I'm going to close this and reference #33 as this seems to relate to the final revision of the central markdown files.
