### ISSUE TITLE
Theory-to-Practice: gauge difficulty of "Projects/Challenges To Try"

### ISSUE THREAD

**Issue by gofilipa** [DHRI-Curriculum/python#25]
Examples include tutorials for libraries/methods from scraping (requests), cleaning (regex), and data vis (pandas), but are they too advanced? 

Offer options for beginner tutorials, and make the difficulty level clear in the explanation.

**Comment by lmrhody** [comment]
Probably so. You might consider looking at an example from Automating the Boring Stuff for ideas.

**Comment by gofilipa** [comment]
Yes I have a couple of chapters already linked from Automate the Boring Stuff! I'm also linking tutorials from RealPython and Programming Historian.

Coming back to this, I'm adding more more explanation on difficulty level so people know it's going to be more intensive than the workshop. Besides that, I think I'll keep the challenges as they are.
