### ISSUE TITLE
Add hands-on example at end of workshop

### ISSUE THREAD

**Issue by gofilipa** [DHRI-Curriculum/python#27]
Final challenge for workshop, such as web scraping (or other task). Include a downloadable script that is relatively easy to read and understand, which participants can then modify for their own hands-on practice.

Currently working on a challenge with [Beautiful Soup 4](https://www.crummy.com/software/BeautifulSoup/bs4/doc/), but welcoming other suggestions! For the bs4 challenge, participants would download [a ready script](https://github.com/DHRI-Curriculum/python/blob/v2.0-filipa-edits/testSoup.py) and copy/paste the URL that they want to scrape. There are also options for scraping other elements by un-commenting relevant lines.

**Comment by kallewesterling** [comment]
I love the idea of a final challenge! I would check out `requests` as a package rather than `urllib` because it’s so straightforward and simple.

**Comment by gofilipa** [comment]
I'm thinking of switching around the last two lessons (on Libraries and Objects) so that we end on Libraries. This swap makes sense to me for two reasons:

- first, the revised workshop's emphasis on more methods (such as sort, append, etc) should also be accompanied with a smoother transition into objects, which is the best way of understanding methods, and methods vs functions, for example. 
- second, we can end the Library lesson with the challenge where people import `requests` (as per @kallewesterling's suggestion) and have a chance to play around with web scraping. That way, people will finish the workshop with this tough but rewarding challenge where they will hopefully have something tangible from their learning.

My only concern is that I know Patrick Smyth has his reasons for ordering the lessons in the way he did, so I'm a bit hesitant to mess with it. 

@rafadavis what do you think? Welcoming any and all thoughts!

**Comment by rafadavis** [comment]
It sounds good to me, and I don't see any problems in switching.

**Comment by kallewesterling** [comment]
I love your idea with the final project @gofilipa centered around a "Library lesson"!

Don't worry too much about Patrick's ideas with the workshop. These are **your** revisions and this iteration of the workshop is **yours** :)

I would like to revisit, later on, the objects section, as I wonder if that can be a bit too advanced for this workshop (?).. I may be completely wrong, and super-open to discussion, for sure.

**Comment by kallewesterling** [comment]
Hey @gofilipa — no stress, of course, but wanted to check in with you where we're standing with this. Also, is this related/overlapping with #28?

I'm asking as I'm wondering if this is something you think is doable now, or whether we should redirect this as a [![](https://img.shields.io/github/labels/dhri-curriculum/python/wishlist)](../labels/wishlist) item?

**Comment by gofilipa** [comment]
hi @kallewesterling ! Depending on how much I get done this week, I may be able to add this as a final challenge, as a way to send off the workshop participants with something a little more challenging. If I cannot do this by Friday, I'll change the item to a wishlist, since I need to move onto other things (like the glossary) for this workshop.

**Comment by kallewesterling** [comment]
Sounds like a good plan to me!

**Comment by gofilipa** [comment]
Okay so I just added a little challenge at the end of the workshop that has them play around with web scraping, specifically the library Requests. It's literally just the tip of the iceberg, as I'm just having them print status codes and encoding, etc. The reason it's so brief is that I don't want to include any more instruction or complexity to a challenge---the concepts are pretty complex as is. But I'm not sure if it's even worth it to include at this point? I'm copy/pasting the addition below so that people can take a quick look.

For context, this is following up the final lesson on "Objects," where we teach participants how to examine objects by using the `dir()` function. For the challenge, I have them import the Requests module, set up a response object, and examine what methods are attached to that object. Pretty simple, but not sure if the final product is interesting enough or worthwhile to include.

Here's the final challenge:

# Challenge

Let's try out a module for web scraping, called Requests. Requests allows you to send all kinds of queries over web browsers, which we call HTTP requests. It is a relatively easy-to-use module with a lot of features that can yield sophisticated web scraping results. For this challenge, let's get some hands-on practice with using requests, and seeing what we can do with it. 

First, import requests into your REPL: 

```pycon
>>> import requests
```

Then, let's set up a request *object*. Basically, we will declare a variable `r` to represent a website that we want to scrape. After the equal sign `=`, we call the `requests` module, and within that module, a method called `get`, which includes the parameter of the website URL, enclosed in single quotes. For example: 

```pycon
>>> import requests
>>> r = requests.get('https://www.nytimes.com')
```

Now, let's examine that request object. Use the `dir` function to see what methods are available to `r`. Look up any of the methods that seem interesting but unclear to you. Even if you don't understand it---that's okay! This is just the beginning of your exploration with this module. It's the first step to running more robust web scraping experiments. 

## Solution

First, checking out what methods are available to the `r` object: 

```pycon
>>> dir(r)
['__attrs__', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__nonzero__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_content', '_content_consumed', '_next', 'apparent_encoding', 'close', 'connection', 'content', 'cookies', 'elapsed', 'encoding', 'headers', 'history', 'is_permanent_redirect', 'is_redirect', 'iter_content', 'iter_lines', 'json', 'links', 'next', 'ok', 'raise_for_status', 'raw', 'reason', 'request', 'status_code', 'text', 'url']
```

Then, trying out some of the methods:

```pycon
>>> r.status_code
200
>>> r.encoding
'utf-8'
>>> r.cookies
<RequestsCookieJar[Cookie(version=0, name='nyt-a', value='04u7q0SFZ2OpnpLqevHY65', port=None, port_specified=False, domain='.nytimes.com', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=True, expires=1627494229, discard=False, comment=None, comment_url=None, rest={'SameSite': 'none'}, rfc2109=False), Cookie(version=0, name='nyt-gdpr', value='1', port=None, port_specified=False, domain='.nytimes.com', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=1595979829, discard=False, comment=None, comment_url=None, rest={}, rfc2109=False), Cookie(version=0, name='nyt-geo', value='PT', port=None, port_specified=False, domain='.nytimes.com', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=False, expires=1595979829, discard=False, comment=None, comment_url=None, rest={}, rfc2109=False), Cookie(version=0, name='nyt-purr', value='cfhspnahhu', port=None, port_specified=False, domain='.nytimes.com', domain_specified=True, domain_initial_dot=True, path='/', path_specified=True, secure=True, expires=1627494229, discard=False, comment=None, comment_url=None, rest={'SameSite: Lax': None}, rfc2109=False)]>

```

What do these methods do? For the `r.status_code`, the `200` return value means that the request was successful, because 200 is the HTTP code for a successful request. This is opposed to 400 codes, like 404 error, which indicates a failure to reach the website. 

This is just the tip of the iceberg for using requests. In order to get more information, you'll have to read up on the module. Here is [an excellent tutorial](https://scotch.io/tutorials/getting-started-with-python-requests-get-requests) to get started.

**Comment by szweibel** [comment]
Yeah, it's tough, because it's really more the beginning of a new thing to learn rather than a review. But it does build on the skills learned in the workshop. I don't know.

**Comment by kallewesterling** [comment]
I think it would be great to have this at the end, but perhaps we can title it something like "Advanced Final Challenge" and use language in the lesson that frames it as such, and make it sort of "this is something you can try if you'd like"...?

**Comment by gofilipa** [comment]
Thanks for the feedback! I added some text saying "Advanced Challenge" and emphasizing that this is just something to try, and that it's a starting point for further exploration. Going to close out the issue.
