### ISSUE TITLE
Lessons: modify example content to reflect scholarly/humanities tasks 

### ISSUE THREAD

**Issue by gofilipa** [DHRI-Curriculum/python#28]
Some of the examples we use to teach core concepts (like the "weather app" to teach if/elif statements) reference things that might not be totally relevant to the kinds of work that our participants will be doing. We should revise the example content to better prepare and inform the tasks you can achieve with these skills. 

For instance, instead of a weather app, how about a control flow example for cleaning text? 

Welcoming suggestions!

**Comment by lmrhody** [comment]
@gofilipa I like this idea of using the same process but one that works with a task that is more familiar. Do we want to think about a dataset that makes sense to use for this so that we can control the kind of cleaning that needs to be done?

**Comment by kallewesterling** [comment]
Realizing now that you've implemented this already, right, @gofilipa? If so, feel free to close this issue.
