### ISSUE TITLE
Central markdown files finalized

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/python#33]
### `lessons.md`

- [x] Accept any [pending pull requests](../pulls)

- [x] Implement all [the edits/requests](https://github.com/DHRI-Curriculum/python/issues/31) that you have left from your colleagues.

- [x] Add any additional content you think is needed for version 2.0 _and open any other using the [![](https://img.shields.io/github/labels/dhri-curriculum/python/wishlist)](../labels/wishlist) label in your repo

- [x] Ensure the length of each lesson is not too long
    _each section (beginning with a level 1 heading [#]) should be no more than 3-4 paragraphs_

- [x] Ensure temporal references and references to other workshops are removed (since learners will “attend” these workshops mostly asynchronously)

### `frontmatter.md`

- [x] Finalize and streamline all sections

- [x] Ensure your abstract is no longer than ~100 words
   _If you need/want them to be longer, you can create a new first section in lessons.md and put the longer version of the abstract there._

- [x] Resolve any "TBD" content.

- [x] Make sure collaborator lists are complete with roles and links
   _see [Di’s example](https://github.com/DHRI-Curriculum/data-literacies/blob/v2.0-di-edits/frontmatter.md#acknowledgements) but feel free to add links to people’s websites!_

- [x] Ensure all Projects and Readings have "annotations"
   _annotations = 1-2 sentences answering “Why is it important for our learners to read or expose themselves to these readings/projects”? For examples, see [agenda doc](https://docs.google.com/document/d/18MImAjxv3_cYKuGvnvsLS0L8Dkn8jSluMxOjeWv2G8k/edit#)_

### `theory-to-practice.md`

- [x] Finalize and streamline all sections

- [x] Resolve any "TBD" content.

- [x] Ensure all Projects, Readings, and Tutorials have "annotations"
   _annotations = 1-2 sentences answering “Why is it important for our learners to read or expose themselves to these readings/projects”? For examples, see [agenda doc](https://docs.google.com/document/d/18MImAjxv3_cYKuGvnvsLS0L8Dkn8jSluMxOjeWv2G8k/edit#)_

**Comment by gofilipa** [comment]
Because it was a little long, I split up the "Lists & Loops' lesson into two, "Lists" and "Loops", and added an extra challenge to "Lists". The other longer lessons "Input" and "Finding Answers with Google", are also a bit on the longer side, but I couldn't figure out a way to split them without making some major flow changes. Hope that's alright.

**Comment by kallewesterling** [comment]
Sounds good to split up "Lists" and "Loops." They're sort of different things.

I do think that the "Doing Things to Lists," which (I think?) is listed as a subsection under "Input" is quite different from requesting input from the user as well? I might be wrong, so feel free to argue differently :) (I know the Challenge incorporates `input()` but challenges should always be able to refer back to previous lessons, so that's not really an issue as I see it.)

I agree about Finding Answers with Google, though. That one will be longer but it's also more conceptual so I think that's OK :)

**Comment by gofilipa** [comment]
Thanks, @kallewesterling ! I've split up "Input" from "Doing Things to Lists," and added a bit more to flesh out "Input." Things seem more evenly distributed now. Thanks for the tip!

**Comment by kallewesterling** [comment]
Awesome, good to hear!

**Comment by kallewesterling** [comment]
Since we are now done with `sprint 4` and in `sprint 5` and all the checkboxes above are checked, I'll go ahead and close this issue. @gofilipa if you think we should keep it open, feel free to reopen the issue.
