### ISSUE TITLE
Create glossary term files from python

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/python#34]
- [ ] Go through `lessons.md` (and other files) and find all important terms in need of definition to help learners grasp concepts, tools, commands, etc. List the files in a text file, or keep them in this issue feed below, for instance.

- [ ] Add a file to the glossary repository's [`terms`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms) folder called `<term>.md` for each of the terms.

   - [How do I add terms to the glossary?](https://github.com/DHRI-Curriculum/glossary/blob/v2.0/how-to-add-new-terms.md) <— See instructions

**Comment by gofilipa** [comment]
Hi @kallewesterling - can I copy/paste terms descriptions from the [python section of the glossary](https://github.com/DHRI-Curriculum/glossary/blob/master/sections/python.md)? or should I be making descriptions from scratch? Sorry if you've already answered this somewhere else!

**Comment by kallewesterling** [comment]
If you think the existing definitions are good enough, I say go ahead!

**Comment by kallewesterling** [comment]
If you are done with the terms, please see and address this issue: https://github.com/DHRI-Curriculum/glossary/issues/36.

**Comment by gofilipa** [comment]
Hi Kalle,

I finished the terms and pushed them. But I believe I just made a mistake
with the pull request... I pushed to master (oops) and think I got rid of
everyone else's terms... Is there a way to revert this push? I'm still not
a git expert (clearly) so I don't want to experiment with solutions. Sorry
for the inconvenience :/

Filipa

**Comment by kallewesterling** [comment]
All good and fixed now, so I'll go ahead and close out the issue.
