### ISSUE TITLE
The issue that closes them all

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/python#38]
Feel free to close this issue after you have pushed all of your local branch updates to your GitHub repo, so I can initiate a pull request to the `v2.0` branch. (If you feel comfortable and interested in doing it yourself, you can do that as well, of course!)

This is the issue that closes out the v2.0 edits from you. Thank you so very much for all your hard work this summer!

**Comment by gofilipa** [comment]
just pushed my final changes to this repo and closing out! Thank you @kallewesterling !!

**Comment by kallewesterling** [comment]
Thank you so much @gofilipa for all your work!
