### ISSUE TITLE
List error

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/python#40]
Error on this line (reported by Kai Prenger):
https://github.com/DHRI-Curriculum/python/blame/v2.0/lessons.md#L144

```py
["banana, 'coffee', 'eggs']
```

should be

```py
["banana", 'coffee', 'eggs']
```

or

```py
['banana', 'coffee', 'eggs']
```

**Comment by kallewesterling** [comment]
Reported by Kai Prenger [here](https://docs.google.com/document/d/1aTCa8fGt0SUuBTvLxbIkseGkSZ1qTi3YAZhoAHTO6CQ/edit)

**Comment by gofilipa** [comment]
resolved
