### ISSUE TITLE
Move IF/ELSE from Challenge to Body of Lesson 10

### ISSUE THREAD

**Issue by smorello87** [DHRI-Curriculum/python#41]
As is now, it will prevent folks who skip the challenge from going through it, preventing them to understand the logics behind it (which in turn gets in their way when they go through the Text Analysis workshop)

**Comment by kallewesterling** [comment]
Thank you - this is a great suggestion I think @smorello87! What do you think @lmrhody ?

**Comment by kallewesterling** [comment]
Another option is to create a "required" aspect on the challenge, which is a thing I have thought of in the past too! That could make it into something that our learners _need to_ focus on, as an exercise.

**Comment by gofilipa** [comment]
I added a "required" statement in the challenge and some text in the body of the lesson specifying that this challenge is necessary in order to understand and complete further workshop tasks.
