### ISSUE TITLE
in loops.md fix code for printing 2nd item in list

### ISSUE THREAD

**Issue by lmrhody** [DHRI-Curriculum/python#9]
Looks like we copied the same line for 2 items in the list. 
when printing names of flowers using number in list, the second flower (violets) should use number 2, not one, no? Is this intentional so that they go back to fix it?

**Comment by smythp** [comment]
Good catch on the repeat. The second item is actually supposed to be list index 1, since Python counts from 0. Also added a note about counting from 0, which I usually say but didn't include here.
